
#ifndef _HARDWARE_INCLUDED
#define _HARDWARE_INCLUDED

//#define STM32F1XX_BM_TIMER_SYSTICK_HARDWARE
//	#define HCLK_VALUE		8000000

//#define BUZZER_BM_HARDWARE
	#define BUZZER_ACTIVE       1     
  #define BUZZER_PIN          1
  #define BUZZER_GPIO         GPIOA

#endif		// _HARDWARE_INCLUDED